### ISSUE TITLE
Reporte de Entrevista

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-balam#2]
[Reporte de Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-balam/files/9464191/Reporte.de.Entrevista.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
Calificacion 20
